version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us -est-1)



  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-repo .

  post_build:
    commands:
      - docker tag my-repo:latest 875681151031.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
      - docker push 875681151031.dkr.ecr.us--est-1.amazonaws.com/my-repo:latest

      # Stop and remove existing containers
      - docker-compose -f docker-compose.yml down

      # Pull the latest images from ECR
      - docker-compose -f docker-compose.yml pull

      # Start the updated containers
      - docker-compose -f docker-compose.yml up -d

artifacts:
  files:
    - '**/*'

