version: 0.2

env:
  variables:
    REPO_URL_1: "public.ecr.aws/y1w7a2c8/my-repo"
    REPO_URL_2: "875681151031.dkr.ecr.us-east-1.amazonaws.com/my-repo"
phases:
  install:
    runtime-versions:
      docker: 23

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URL_2



  build:
    commands:
      - echo Build started on `date`
      - docker-compose -f docker-compose.yml build

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker-compose -f docker-compose.yml push
      - echo Deploying Docker Compose...

      # Stop and remove existing containers
      - docker-compose -f docker-compose.yml down

      # Pull the latest images from ECR
      - docker-compose -f docker-compose.yml pull

      # Start the updated containers
      - docker-compose -f docker-compose.yml up -d

artifacts:
  files:
    - '**/*'

