version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875681151031.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker-compose -f docker-compose.yml build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose -f docker-compose.yml push

      # Add any additional deployment steps here
      # For example, you could use Docker Compose to run your application
      # on the EC2 instance directly or use a different deployment method.

artifacts:
  files:
    - '**/*'

